Exercício 1:
O primeiro exercício consiste em seguir uma série de instruções utilizando o NumPy, incluindo a criação de arrays multidimensionais, preenchimento com valores específicos e operações matemáticas. Vamos analisar passo a passo como resolver esse exercício.

Criar um array 6×6 preenchido com 0


In [46]:
import numpy as np
a = np.zeros((6,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Preencher o centro desse array com um array 4×4 preenchido com 1

In [47]:
b = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
a[1:5, 1:5]=b #Seleção da submatriz
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

Preencher o centro desse array com um array 2×2

In [48]:
c = np.array([[2,2],[2,2]])
a[2:4, 2:4]=c
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

Gerar um segundo array 6×6 com números inteiros aleatórios entre 0 e 2

In [56]:
d = np.random.randint(0,3, size=(6,6))
d

array([[2, 2, 1, 0, 2, 2],
       [0, 1, 2, 0, 0, 1],
       [1, 1, 1, 2, 1, 2],
       [2, 1, 1, 0, 0, 2],
       [2, 1, 2, 0, 1, 1],
       [2, 2, 2, 1, 1, 0]])

Subtrair o primeiro array do segundo array

In [62]:
c_tiled = np.tile(c, (3,3))
c_tiled
result = a - c_tiled
result

array([[-2., -2., -2., -2., -2., -2.],
       [-2., -1., -1., -1., -1., -2.],
       [-2., -1.,  0.,  0., -1., -2.],
       [-2., -1.,  0.,  0., -1., -2.],
       [-2., -1., -1., -1., -1., -2.],
       [-2., -2., -2., -2., -2., -2.]])