   Crie um array NumPy de 1 a 10. 

In [2]:
import numpy as np
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

  Crie um array 3x3 preenchido com zeros. 

In [9]:
a = np.full((3,3), 0)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

  Crie um array 2x4 preenchido com uns.

In [10]:
b = np.full((2,4), 1)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

   Crie um array NumPy com valores de 10 a 50 com intervalo de 5 em 5. 

In [11]:
c = np.arange(10,51,5)
c

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

   Crie um array 1D com 10 elementos e altere sua forma para 2D (5x2). 

In [19]:
e = np.arange(10)
e2 = e.reshape(5,2)
e2.ndim

2

   Dado o array `a = np.array([1, 2, 3, 4, 5, 6])`, selecione os elementos de índice 1, 3 e 4. 

In [26]:
a = np.array([1, 2, 3, 4, 5, 6])
a[1],a[3],a[4]

(2, 4, 5)

   Dado o array `a = np.array([10, 20, 30, 40, 50])`, selecione os elementos do índice 1 ao 3. 

In [29]:
a = np.array([10, 20, 30, 40, 50])
a[1:4]

array([20, 30, 40])

Crie dois arrays `a = np.array([1, 2, 3])` e `b = np.array([4, 5, 6])`, e calcule a soma, a subtração e a multiplicação elemento a elemento. 

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
soma = np.add(a,b)
sub = np.subtract(a,b)
mult = np.multiply(a,b)
sub, s, mult

(array([-3, -3, -3]), array([5, 7, 9]), array([ 4, 10, 18]))

   Dado o array `a = np.array([1, 2, 3, 4])`, calcule a soma de todos os elementos. 

In [12]:
a = np.array([1,2,3,4])
s = np.sum(a)
s

10

Dado o array `a = np.array([4, 2, 8, 6])`, encontre o valor máximo e o valor mínimo. 

In [14]:
a = np.array([4,2,8,6])
maximo = np.max(a)
minimo = np.min(a)
maximo, minimo

(8, 2)

Calcule a média e o desvio padrão do array `a = np.array([1, 2, 3, 4, 5])`. 

Desvio padrão é uma medida que expressa o grau de dispersão de um conjunto de valores, indicando a uniformidade desses dados.
Quanto mais perto de 0 for o desvio padrão, mais homogêneo é o conjunto de dados.

In [17]:
a = np.array([1, 2, 3, 4, 5])
media = np.mean(a)
media
dp = np.std(a)
dp

1.4142135623730951

Dada uma matriz 2D `a = np.array([[1, 2], [3, 4]])`, calcule a transposta. 

Uma matriz transposta é como se fosse o "contrário" de uma matriz de referência.

In [19]:
a = np.array([[1,2],[3,4]])
a.T

array([[1, 3],
       [2, 4]])

Dadas as matrizes `A = np.array([[1, 2], [3, 4]])` e `B = np.array([[5, 6], [7, 8]])`, calcule o produto matricial.

Produto matricial: É a multiplicação de duas matrizes A e B, é possível quando o número de colunas de A é igual ao número de linhas de B.

Se M1 é uma matriz m×n e M2 é uma matriz n×p, então seu produto é uma matriz m×p

In [22]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])
A @ B

array([[19, 22],
       [43, 50]])